# Default values for rnacos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: qingpan/rnacos
  pullPolicy: Always # IfNotPresent #
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# DEPRECATED: rancosConfig is deprecated, please use env instead
# 已废弃：rancosConfig 已废弃，请使用 env 配置
rancosConfig:
  rustLog: info
  httpWorkers: 8
  consoleLoginOneHourLimit: 5

# DEPRECATED: extraEnvVars is deprecated, please use env instead
# 已废弃：extraEnvVars 已废弃，请使用 extraEnv 配置
extraEnvVars: []


# 额外的环境变量配置
# more configs from environment variables
# https://r-nacos.github.io/docs/env_config/
extraEnv:
  # 推荐的配置方式 (Recommended configuration)
  RNACOS_HTTP_PORT: 8848
  RNACOS_GRPC_PORT: 9848
  RNACOS_HTTP_CONSOLE_PORT: 10848
  RUST_LOG: "info"                              # 替代 rancosConfig.rustLog
  RNACOS_HTTP_WORKERS: 8                        # 替代 rancosConfig.httpWorkers  
  RNACOS_CONSOLE_LOGIN_ONE_HOUR_LIMIT: 5        # 替代 rancosConfig.consoleLoginOneHourLimit
  # 其他示例环境变量 (Other example environment variables)
  # RNACOS_DATA_DIR: "/nacos/"
  # RNACOS_ENABLE_NO_AUTH_CONSOLE: "false"
  # RNACOS_BACKUP_TOKEN: ""
  # RNACOS_INIT_ADMIN_USERNAME: "admin"
  # RNACOS_INIT_ADMIN_PASSWORD: "admin"

# 从 ConfigMap 或 Secret 引用的环境变量
envFrom: []
  # - configMapRef:
  #     name: rnacos-config
  # - secretRef:
  #     name: rnacos-secret

persistence:
  size: 20Gi
  storageClass: default
  accessModes: ["ReadWriteOnce"]
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 10848

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: rnacos.example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
