apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rnacos.fullname" . }}
  labels:
    {{- include "rnacos.labels" . | nindent 4 }}
data:
  entrypoint.sh: |-
    # 1. 读取当前ip
    export RNACOS_RAFT_NODE_ADDR={{ include "rnacos.fullname" . }}-$(echo $MY_POD_NAME | grep -o '[0-9]\+$').{{ include "rnacos.fullname" . }}-headless:{{ .Values.extraEnv.RNACOS_GRPC_PORT | default 9848 }}
    export RNACOS_RAFT_NODE_ID=$(expr 1 + $(echo $MY_POD_NAME | grep -o '[0-9]\+$'))
    export RNACOS_RAFT_JOIN_ADDR={{ include "rnacos.fullname" . }}-0.{{ include "rnacos.fullname" . }}-headless:{{ .Values.extraEnv.RNACOS_GRPC_PORT | default 9848 }}
    # export RNACOS_RAFT_AUTO_INIT=true
    
    # 优先使用 extraEnv 配置，向下兼容 rancosConfig (DEPRECATED)
    # Priority: extraEnv config, fallback to rancosConfig (DEPRECATED)
    export RUST_LOG={{ .Values.extraEnv.RUST_LOG | default .Values.rancosConfig.rustLog }}
    export RNACOS_HTTP_WORKERS={{ .Values.extraEnv.RNACOS_HTTP_WORKERS | default .Values.rancosConfig.httpWorkers }}
    export RNACOS_CONSOLE_LOGIN_ONE_HOUR_LIMIT={{ .Values.extraEnv.RNACOS_CONSOLE_LOGIN_ONE_HOUR_LIMIT | default .Values.rancosConfig.consoleLoginOneHourLimit }}
    
    echo $RNACOS_RAFT_NODE_ADDR
    echo $RNACOS_RAFT_NODE_ID
    echo $RNACOS_RAFT_JOIN_ADDR
    exec /usr/bin/rnacos
