apiVersion: v1
kind: Service
metadata:
  name: {{ include "rnacos.fullname" . }}
  labels:
    {{- include "rnacos.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.extraEnv.RNACOS_HTTP_PORT | default 8848 }}
      targetPort: {{ .Values.extraEnv.RNACOS_HTTP_PORT | default 8848 }}
      protocol: TCP
      name: http
    - port: {{ .Values.extraEnv.RNACOS_GRPC_PORT | default 9848 }}
      targetPort: {{ .Values.extraEnv.RNACOS_GRPC_PORT | default 9848 }}
      protocol: TCP
      name: grpc
    - port: {{ .Values.extraEnv.RNACOS_HTTP_CONSOLE_PORT | default 10848 }}
      targetPort: {{ .Values.extraEnv.RNACOS_HTTP_CONSOLE_PORT | default 10848 }}
      protocol: TCP
      name: admin
  selector:
    {{- include "rnacos.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rnacos.fullname" . }}-headless
  labels:
    {{- include "rnacos.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.extraEnv.RNACOS_HTTP_PORT | default 8848 }}
      targetPort: {{ .Values.extraEnv.RNACOS_HTTP_PORT | default 8848 }}
      protocol: TCP
      name: http
    - port: {{ .Values.extraEnv.RNACOS_GRPC_PORT | default 9848 }}
      targetPort: {{ .Values.extraEnv.RNACOS_GRPC_PORT | default 9848 }}
      protocol: TCP
      name: grpc
    - port: {{ .Values.extraEnv.RNACOS_HTTP_CONSOLE_PORT | default 10848 }}
      targetPort: {{ .Values.extraEnv.RNACOS_HTTP_CONSOLE_PORT | default 10848 }}
      protocol: TCP
      name: admin
  selector:
    {{- include "rnacos.selectorLabels" . | nindent 4 }}

