apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rnacos.fullname" . }}
spec:
  serviceName: {{ include "rnacos.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rnacos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rnacos.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rnacos.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.extraEnv.RNACOS_HTTP_PORT | default 8848 }}
              protocol: TCP
              name: http
            - containerPort: {{ .Values.extraEnv.RNACOS_GRPC_PORT | default 9848 }}
              protocol: TCP
              name: grpc
            - containerPort: {{ .Values.extraEnv.RNACOS_HTTP_CONSOLE_PORT | default 10848 }}
              protocol: TCP
              name: admin
          command:
            - /bin/sh
            - /io/entrypoint.sh
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.extraEnv.RNACOS_HTTP_PORT | default 8848 }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.extraEnv.RNACOS_HTTP_PORT | default 8848 }}
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- with .Values.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- range $key, $value := .Values.extraEnv }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- with .Values.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
            - mountPath: /io/entrypoint.sh
              name: {{ include "rnacos.fullname" . }}
              subPath: entrypoint.sh
            - name: {{ include "rnacos.fullname" . }}-pvc
              mountPath: /io/nacos_db
      volumes:
        - name: podinfo
          emptyDir: {}
        - name: {{ include "rnacos.fullname" . }}
          configMap:
            name: {{ include "rnacos.fullname" . }}
  volumeClaimTemplates:
  - metadata:
      name: {{ include "rnacos.fullname" . }}-pvc
    spec:
      {{- with .Values.persistence.accessModes }}
      accessModes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      storageClassName: {{ .Values.persistence.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
